config/routes.rb
Filmbase::Application.routes.draw do

  resources :people

  resources :genres

  resources :countries

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :films do 
    member do
      get 'autf'
      get :users
    end
    resources :themes do
      resources :comments
    end
  end
  

   root :to => "films#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_one :theme

  has_attached_file :image, :styles => { :medium => "200x", :thumb => "64x" },    :convert_options => {:thumb => "-gravity center -extent 64x"}
  belongs_to :user
  validates_attachment_content_type :image, :content_type=>/^image\/(gif|png|x\-png|jpeg|jpg|pjpeg)$/
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :check_regular_user
  before_filter :moderator
  # GET /comments
  # GET /comments.xml
  def index
    @film = Film.find(params[:film_id])
    @theme = Theme.find(params[:theme_id])
    @comments = Comment.where(:theme_id=>@theme.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @film = Film.find(params[:film_id])
    @theme = Theme.find(params[:theme_id])
    @comment = @theme.comments.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @film = Film.find(params[:film_id])
    @theme = Theme.find(params[:theme_id])
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @theme = Theme.find(params[:theme_id])
    @comment = @theme.comments.build(params[:comment])
    if @current_user
      @comment.commenter = @current_user.login
    end

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(film_theme_comments_path, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(film_theme_comments_path, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(film_theme_comments_path) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.theme
  .title
    =l comment.created_at, :format=>:long
    .right
      \#
      =@count
  .cuser=comment.commenter
  .cbody
    -if comment.image?
      =image_tag comment.image.url(:medium)
    =comment.body
  .clear

app/views/comments/_form.html.haml
= form_for [@film, @theme, @comment], :html=>{:multipart=>true} do |f|
  -if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :image, "Прикрепить изображение:"
    = f.file_field :image
  .field
    = f.label :body
    = f.text_area :body
  .field
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', film_theme_comment_path(@film, @theme, @comment)
\|
= link_to 'Back', film_theme_comments_path(@film, @theme)

app/views/comments/index.html.haml
%h1 Комментарии

-if @theme.image?
  =image_tag(@theme.image.url(:medium))
-@count = 0
-@comments.each do |comment|
  -@count += 1
  =render 'comments/comment', :comment=>comment
  =link_to "Редактировать", edit_film_theme_comment_path(@film, @theme, comment)
  \|
  =link_to "Удалить", film_theme_comment_path(@film, @theme, comment), :confirm =>"Вы уверены?", :method => :delete
-if !@theme.image?
  =form_for [@film,@theme], :html=>{:multipart=>true} do |t|
    Прикрепить изображение:
    %br
    =t.file_field :image
    %br
    =t.submit
%br

=link_to "Добавить комментарий", new_film_theme_comment_path
\|
=link_to "Назад", film_themes_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', film_theme_comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @comment.body
%p
  %b Commenter:
  = @comment.commenter
%p
  %b Theme:
  = @comment.theme_id

= link_to 'Edit', edit_film_theme_comment_path(@comment)
\|
= link_to 'Back', film_theme_comments_path