config/routes.rb
Filmbase::Application.routes.draw do

  resources :people

  resources :genres

  resources :countries

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :films do 
    member do
      get 'autf'
      get :users
    end
    resources :themes do
      resources :comments
    end
  end
  

   root :to => "films#index"

end

app/models/theme.rb
class Theme < ActiveRecord::Base
  has_one :film
  has_many :comments

  has_attached_file :image, :styles => { :medium => "200x", :thumb => "64x" }

  validates_attachment_content_type :image, :content_type=>/^image\/(gif|png|x\-png|jpeg|jpg|pjpeg)$/
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_filter :check_regular_user
  before_filter :moderator
  # GET /themes
  # GET /themes.xml
  def index
    @film = Film.find(params[:film_id])
    @themes = Theme.where(:film_id => params[:film_id]).page(params[:page])
    @user = User.find(@film.user_id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @themes }
    end
  end

  # GET /themes/1
  # GET /themes/1.xml
  def show
    @theme = Theme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @theme }
    end
  end

  # GET /themes/new
  # GET /themes/new.xml
  def new
    @film = Film.find(params[:film_id])
    @theme = @film.themes.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @theme }
    end
  end

  # GET /themes/1/edit
  def edit
    @theme = Theme.find(params[:id])
    @film = Film.find(params[:film_id])
  end

  # POST /themes
  # POST /themes.xml
  def create
    @film = Film.find(params[:film_id])
    @theme = @film.themes.build params[:theme]

    respond_to do |format|
      if @theme.save
        format.html { redirect_to(film_themes_path, :notice => 'Theme was successfully created.') }
        format.xml  { render :xml => @theme, :status => :created, :location => @theme }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @theme.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /themes/1
  # PUT /themes/1.xml
  def update
    @theme = Theme.find(params[:id])

    respond_to do |format|
      if @theme.update_attributes(params[:theme])
        format.html { redirect_to(film_themes_path, :notice => 'Theme was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @theme.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.xml
  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to(film_themes_path) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.haml
= form_for [@film, @theme] do |f|
  -if @theme.errors.any?
    #error_explanation
      %h2= "#{pluralize(@theme.errors.count, "error")} prohibited this theme from being saved:"
      %ul
        - @theme.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/themes/_theme.html.haml
.theme
  .left=link_to image_tag('theme_thumb.png'), film_theme_comments_path(@film, theme)
  .col
    =link_to theme.name, film_theme_comments_path(@film, theme)
    .low
      =l(theme.created_at, :format=>:long)
    .center
      Комментариев: 
      =theme.comments.count
  .clear

app/views/themes/edit.html.haml
%h1 Editing theme

= render 'form'

= link_to 'Show', film_theme_path(@film, @theme)
\|
= link_to 'Back', film_themes_path

app/views/themes/index.html.haml
%h1="Список тем к фильму: " + @film.name

-@themes.each do |theme|
  =render 'themes/theme', :theme=>theme
=paginate @themes

-if @current_user && @current_user.admin?
  =link_to "Добавить тему", new_film_theme_path
  \|
=link_to "Назад", film_path(@film)

app/views/themes/new.html.haml
%h1 New theme

= render 'form'

= link_to 'Back', films_path

app/views/themes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @theme.name

 

= link_to 'Edit', edit_film_theme_path(@theme)
\|
= link_to 'Back', film_themes_path