config/routes.rb
Filmbase::Application.routes.draw do

  resources :people

  resources :genres

  resources :countries

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :films do 
    member do
      get 'autf'
      get :users
    end
    resources :themes do
      resources :comments
    end
  end
  

   root :to => "films#index"

end

app/models/film.rb
class Film < ActiveRecord::Base

  scope :full_load, includes(:genre, :country, :director, :people)

  belongs_to :country
  belongs_to :director,:class_name => "Person"
  belongs_to :genre
  has_and_belongs_to_many :users
  has_and_belongs_to_many :people,:order => 'name'
  has_attached_file :cover, :styles => { :medium => "200x", :thumb => "64x" }
  has_many :themes
  
  
  validates_attachment_content_type :cover,:content_type=>/^image\/(gif|png|x\-png|jpeg|jpg|pjpeg)$/
  validates :name,:presence=>true
  validates :country_id,:presence => true
  validates :genre_id,:presence => true
  validates :length,:numericality => {:only_integer=>true,:greater_than=>0},:allow_blank => true
  validates :year,:numericality => {:only_integer=>true,:greater_than=>1900},:allow_blank => true
  validates :trailer_url,:format => /\w+/i,:allow_blank => true
  attr_reader :person_tokens

  def person_tokens=(ids)
    self.person_ids = ids.split(",")
  end

  def can_be_edited?(user)
    user && user.admin?
  end

  def title
    res=name
    res+=" (#{year})" if year
    res
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_filter :check_admin_user, :except=>['index', 'show', 'themes', 'users', 'autf']
  before_filter :check_user_presence, :only=>'show'

  def index
    @films = Film.page(params[:page])
  end

  def show
    @film = Film.full_load.find(params[:id])
    @current_genre=@film.genre #for layout
    @count = @film.users.count
  end

  def new
    @film = Film.new
  end

  def edit
    @film = Film.full_load.find(params[:id])
  end

  def create
    @film = Film.new(params[:film])
    if @film.save
      redirect_to @film, :notice => 'Фильм добавлен.'
    else
      render :action => "new"
    end
  end

  def update
    @film = Film.full_load.find(params[:id])
    if @film.update_attributes(params[:film])
      redirect_to @film, :notice => 'Фильм сохранен.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    redirect_to films_url, :notice=>"Фильм удален"
  end
  def autf
    @film = Film.find(params[:id])
    @user = @current_user
    if @film.users.include? @user
     redirect_to film_themes_path(@film)
    else 
    @film.users << @user
     redirect_to film_path(@film), :notice=>"Вы успешно вступили в группу"
    end 
  end

  def users
    @film = Film.find(params[:id])
    @users = @film.users
  end
end

app/helpers/films_helper.rb
module FilmsHelper
  def show_video(url)
    content_tag(:iframe,nil,:width=>"480",:height=>"390",:src=>"http://www.youtube.com/embed/#{url}",:frameborder=>0,:allow_fullscreen=>true)
  end
end

app/views/films/_film.html.haml
.film
  .left=link_to image_tag(film.cover? ? film.cover.url(:thumb) : 'video_thumb.png'),film
  .col
    =link_to film.title,film
    -unless film.origin_name.blank?
      .low=film.origin_name
  .clear

app/views/films/_form.html.haml
=form_for @film,:html=>{:multipart=>true} do |f|
  -if @film.errors.any?
    .div.error
      %h2 При сохранении произошли ошибки
      %ul
        -@film.errors.full_messages.each do |msg|
          %li=msg
  .field
    =f.label :name
    %br
    =f.text_field :name
  .field
    =f.label :origin_name
    %br
    =f.text_field :origin_name
  .field
    =f.label :slogan
    %br
    =f.text_area :slogan
  .field
    =f.label :country_id
    %br
    =f.select :country_id,Country.all.map{|c| [c.name,c.id]}
  .field
    =f.label :genre_id
    %br
    =f.select :genre_id,Genre.all.map{|g| [g.name,g.id]}
  .field
    =f.label :director_id
    %br
    =f.select :director_id,Person.order('name').all.map{|p| [p.name,p.id]}
  .field
    =f.label :year
    %br
    =f.text_field :year,:size=>4
  .field
    =f.label :length
    %br
    =f.text_field :length,:size=>3
  .field
    =f.label :person_tokens, "В главных ролях"
    %br
    =f.text_field :person_tokens,"data-pre"=>@film.people.map(&:attributes).to_json
  .field
    =f.label :user_id
    %br
    =f.select :user_id,User.order('login').all.map{|p| [p.login,p.id]}
  .field
    =f.label :cover
    %br
    =f.file_field :cover
  .field
    =f.label :trailer_url, "Код видео на YouTube.com"
    %br
    =f.text_field :trailer_url
  .actions
    =f.submit

app/views/films/_themes.html.haml
%h1 Listing themes

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @themes.each do |theme|
    %tr
      %td= theme.name
      %td= theme.film_id
      %td= link_to 'Show', theme
      %td= link_to 'Edit', edit_theme_path(theme)
      %td= link_to 'Destroy', theme, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Theme', new_theme_path

app/views/films/edit.html.haml
%h1 Редактирование фильма
= render 'form'
= link_to 'Показать', @film
\|
= link_to 'Назад', films_path

app/views/films/index.html.haml
%h1 Фильмы
-@films.each do |film|
  =render 'films/film',:film=>film
=paginate @films
-if @current_user && @current_user.admin?
  =link_to "Добавить фильм",new_film_path

app/views/films/new.html.haml
%h1 Новый фильм
=render 'form'
=link_to 'Назад',films_path

app/views/films/show.html.haml
%h1=@film.name
-unless @film.origin_name.blank?
  %h2=@film.origin_name
-unless @film.slogan.blank?
  %em.smaller &laquo;#{@film.slogan}&raquo;
.left
  =image_tag(@film.cover? ? @film.cover.url(:medium) : 'video.png',:alt=>@film.name)
  .tlist
    -if @access && @current_user
      =link_to "Вступить в группу", autf_film_path(@path)
      (
      =link_to "Нас уже: "+@count.to_s+" ", users_film_path
      )
    -elsif !@access
      =link_to "Список тем", autf_film_path(@path)
.col
  %dl
    %dt=Film.human_attribute_name(:country_id)
    %dd=@film.country.name
    %dt=Film.human_attribute_name(:genre_id)
    %dd=link_to @film.genre.name,@film.genre
    %dt=Film.human_attribute_name(:director_id)
    %dd=link_to @film.director.name,@film.director
    -if @film.year
      %dt=Film.human_attribute_name(:year)
      %dd=@film.year
    -if @film.length
      %dt=Film.human_attribute_name(:length)
      %dd
        =@film.length
        мин
    -unless @film.people.blank?
      %dt В главных ролях
      %dd
        -@film.people.each do |person|
          =render 'people/person',:person=>person
    -unless @film.description.blank?
      %dt=Film.human_attribute_name(:description)
      %dd=@film.description
    -unless @film.trailer_url.blank?
      %dt=Film.human_attribute_name(:trailer_url)
      %dd=show_video(@film.trailer_url)
  =link_to "К списку фильмов",films_path
  .field
  -if @film.can_be_edited?(@current_user)
    \|
    =link_to "Редактировать",edit_film_path(@path)
    \|
    =link_to "Удалить",@film,:confirm => "Вы уверены?",:method => :delete

app/views/films/themes.html.haml
%h1 Listing themes

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @themes.each do |theme|
    %tr
      %td= theme.name
      %td= theme.film_id
      %td= link_to 'Show', theme
      %td= link_to 'Edit', edit_theme_path(theme)
      %td= link_to 'Destroy', theme, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Theme', new_theme_path

app/views/films/users.html.haml
%h1 Участники обсуждения

%table
  %tr
    %th Пользователи

  -@users.each do |user|
    %tr
      %td=user.login
%br
=link_to "Назад", film_path(@film)