config/routes.rb
Filmbase::Application.routes.draw do

  resources :people

  resources :genres

  resources :countries

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :films do 
    member do
      get 'autf'
      get :users
    end
    resources :themes do
      resources :comments
    end
  end
  

   root :to => "films#index"

end

app/views/layouts/_aside.haml
#aside.box
  .padding.box
    %p#logo= link_to image_tag("logo.png", :alt=>"Видео каталог"), root_path
  %ul.box
    -Genre.all.each do |genre|
      %li{:id=>genre==@current_genre ? "submenu-active" : nil}=link_to genre.name,genre

app/views/layouts/_footer.haml
#footer.box
  %p.f-left
    &copy;
    =show_years
    Видеокаталог

app/views/layouts/_menu.haml
#menu.box
  %ul.box
    %li{:id=>controller_name=='films' ? "menu-active" : nil}=link_to content_tag(:span,"Фильмы"),films_path
    %li{:id=>controller_name=='people' ? "menu-active" : nil}=link_to content_tag(:span,"Персоны"),people_path
    -if @current_user && @current_user.admin?
      %li{:id=>controller_name=='countries' ? "menu-active" : nil}=link_to content_tag(:span,"Страны"),countries_path
      %li{:id=>controller_name=='genres' ? "menu-active" : nil}=link_to content_tag(:span,"Жанры"),genres_path

app/views/layouts/_tray.haml
#tray.box
  %p.box.f-left
    -if @current_user
      Роль:
      %strong=@current_user.human_role
  %p.f-right
    -if @current_user
      Вы:
      %strong=@current_user.login
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      %strong=link_to "Выход",logout_path,:id=>"logout"
    -else
      %strong=link_to "Регистрация",signup_path
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      %strong=link_to "Вход",login_path,:id=>"login"

app/views/layouts/application.haml
!!!
%html
  %head
    %title Видеокаталог
    = stylesheet_link_tag 'reset', 'main', '2col', 'style', 'mystyle','token-input-facebook'
    /[if lte IE 6]
      =stylesheet_link_tag 'main-ie6'
    =javascript_include_tag :defaults,'jquery.tokeninput'
    = csrf_meta_tag
  %body
    #main
      = render 'layouts/tray'
      %hr.noscreen
      = render 'layouts/menu'
      %hr.noscreen
      #cols.box
        = render 'layouts/aside'
        %hr.noscreen
        #content.box
          -unless notice.blank?
            .msg.done=notice
          -unless flash[:error].blank?
            .msg.error=flash[:error]
          = yield
      %hr.noscreen
      = render 'layouts/footer'